version: '3'

services:
  # FastAPI Uygulaması
  fastapi-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    env_file: .env 

  # MySQL Veritabanı
  mysql-db:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:8888"
